### ISSUE TITLE
About the severity used in Table 1

### ISSUE THREAD

**Issue by hongxin001** [yaodongyu/ProjNorm#1]
Hi Yaodong,

Thanks for your great work. Recently, I am trying to replicate your results in Table 1, but I am not sure which severity you used for the results in Table 1. Could you elaborate some details on this?

Best Regards,
Hongxin

**Comment by yaodongyu** [comment]
Hi Hongxin,

Thank you for your interest in our work! 

Regarding Table 1 in our ProjNorm paper (https://proceedings.mlr.press/v162/yu22i/yu22i.pdf), we used 18 types of corruption with 5 severity levels on CIFAR10 and CIFAR100 (mentioned in Datasets paragraph in Section 3). More specifically, as shown in Figure 2, we scatter plotted both the InD (in-distribution) and 18 corruptions (every corruption corresponds to one type of marker with one color, and every corruption has 5 points in the plot since every corruption contains 5 severity levels).

Please let me know if you have any further questions!

Best,
Yaodong
